function bbox = point2bbox(bboxPolygon)

bbox = [max(1,round(bboxPolygon(1))), max(1,round(bboxPolygon(2))), ...
                round(bboxPolygon(3))-round(bboxPolygon(1)), ...
                round(bboxPolygon(8))-round(bboxPolygon(2))];